apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: restore-camunda-wf
spec:
  serviceAccountName: argo-workflow
  entrypoint: main
  arguments:
    parameters:
    - name: RELEASE_NAME
      value: "camunda"
    - name: NAMESPACE
      value: "camunda"
    - name: VALUE_FILE
      value: "https://raw.githubusercontent.com/ManuelDittmar/camunda-deployment/main/workflows/templates/camunda-values.yaml"
    - name: VERSION
      value: "10.2.1"
    - name: sequence-start
      value: "0"
    - name: sequence-end
      value: "2"
    - name: IMAGE
      value: "camunda/zeebe:8.5.5"
    - name: ZEEBE_RESTORE_FROM_BACKUP_ID
      value: "20240723094537"
    - name: ZEEBE_BROKER_DATA_BACKUP_STORE
      value: "S3"
    - name: ZEEBE_BROKER_DATA_BACKUP_S3_BUCKETNAME
      value: "zeebe-backup"
    - name: ZEEBE_BROKER_DATA_BACKUP_S3_FORCEPATHSTYLEACCESS
      value: "true"
    - name: S3_ENDPOINT
      value: "http://camunda-backup-minio:9000"
    - name: ZEEBE_BROKER_DATA_BACKUP_S3_ACCESSKEY
      value: "minioadmin"
    - name: ZEEBE_BROKER_DATA_BACKUP_S3_SECRETKEY
      value: "minioadmin"
    - name: ZEEBE_BROKER_DATA_BACKUP_S3_REGION
      value: "us-east-1"
    - name: ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT
      value: "3"
    - name: ZEEBE_BROKER_CLUSTER_CLUSTERSIZE
      value: "3"
    - name: ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR
      value: "3"
    - name: ELASTICSEARCH_ENDPOINT
      value: "http://{{workflow.parameters.RELEASE_NAME}}-elasticsearch:9200"
  templates:
  - name: main
    steps:
    - - name: install-camunda
        template: install-camunda
    - - name: scale-down-camunda
        template: scale-down-camunda
    - - name: restore-camunda
        template: restore-camunda
    - - name: scale-up-camunda
        template: scale-up-camunda
  - name: install-camunda
    steps:
    - - name: install-camunda
        templateRef:
              name: install-camunda
              template: install-camunda
        arguments:
          parameters:
          - name: release-name
            value: "{{workflow.parameters.RELEASE_NAME}}"
          - name: helm-namespace
            value: "{{workflow.parameters.NAMESPACE}}"
          - name: values-file
            value: "{{workflow.parameters.VALUE_FILE}}"
          - name: version
            value: "{{workflow.parameters.VERSION}}"
  - name: scale-down-camunda
    steps:
    - - name: upgrade-camunda
        templateRef:
                name: upgrade-camunda
                template: upgrade-camunda
        arguments:
          parameters:
          - name: release-name
            value: "{{workflow.parameters.RELEASE_NAME}}"
          - name: helm-namespace
            value: "{{workflow.parameters.NAMESPACE}}"
          - name: values-file
            value: "{{workflow.parameters.VALUE_FILE}}"
          - name: zeebe-cluster-size
            value: "0"
          - name: operate-enabled
            value: "false"
          - name: optimize-enabled
            value: "false"
          - name: tasklist-enabled
            value: "false"
          - name: connectors-enabled
            value: "false"
  - name: restore-camunda
    dag:
      tasks:
      - name: restore-webapps
        template: restore-webapps
      - name: restore-zeebe
        template: restore-zeebe
  - name: restore-webapps
    steps:
    - - name: elastic-delete-indices
        templateRef:
              name: elastic-delete-indices
              template: elastic-delete-indices
        arguments:
          parameters:
          - name: elasticsearch-endpoint
            value: "{{workflow.parameters.ELASTICSEARCH_ENDPOINT}}"
    - - name: register-snapshots
        templateRef:
          name: register-snapshot
          template: register-snapshot
        withItems:
        - zeebe-backup
        - operate-backup
        - tasklist-backup
        - optimize-backup
        arguments:
          parameters:
          - name: bucket
            value: "{{item}}"
          - name: s3-endpoint
            value: "{{workflow.parameters.S3_ENDPOINT}}"
          - name: elasticsearch-endpoint
            value: "{{workflow.parameters.ELASTICSEARCH_ENDPOINT}}"
    - - name: restore-snapshot
        templateRef:
            name: restore-snapshot
            template: restore-snapshot
        withItems:
        - zeebe-backup
        - operate-backup
        - tasklist-backup
        - optimize-backup
        arguments:
          parameters:
          - name: elasticsearch-endpoint
            value: "{{workflow.parameters.ELASTICSEARCH_ENDPOINT}}"
          - name: backup-time-id
            value: "{{workflow.parameters.ZEEBE_RESTORE_FROM_BACKUP_ID}}"
          - name: repository
            value: "{{item}}"
  - name: restore-zeebe
    steps:
    - - name: restore-zeebe
        templateRef:
          name: restore-zeebe
          template: restore-zeebe
        withSequence:
          start: "{{workflow.parameters.sequence-start}}"
          end: "{{workflow.parameters.sequence-end}}"
        arguments:
          parameters:
          - name: ZEEBE_BROKER_CLUSTER_NODEID
            value: "{{item}}"
          - name: IMAGE
            value: "{{workflow.parameters.IMAGE}}"
          - name: CLAIM_NAME
            value: "data-{{workflow.parameters.RELEASE_NAME}}-zeebe-{{item}}"
          - name: ZEEBE_RESTORE_FROM_BACKUP_ID
            value: "{{workflow.parameters.ZEEBE_RESTORE_FROM_BACKUP_ID}}"
          - name: ZEEBE_BROKER_DATA_BACKUP_STORE
            value: "{{workflow.parameters.ZEEBE_BROKER_DATA_BACKUP_STORE}}"
          - name: ZEEBE_BROKER_DATA_BACKUP_S3_BUCKETNAME
            value: "{{workflow.parameters.ZEEBE_BROKER_DATA_BACKUP_S3_BUCKETNAME}}"
          - name: ZEEBE_BROKER_DATA_BACKUP_S3_FORCEPATHSTYLEACCESS
            value: "{{workflow.parameters.ZEEBE_BROKER_DATA_BACKUP_S3_FORCEPATHSTYLEACCESS}}"
          - name: ZEEBE_BROKER_DATA_BACKUP_S3_ENDPOINT
            value: "{{workflow.parameters.S3_ENDPOINT}}"
          - name: ZEEBE_BROKER_DATA_BACKUP_S3_ACCESSKEY
            value: "{{workflow.parameters.ZEEBE_BROKER_DATA_BACKUP_S3_ACCESSKEY}}"
          - name: ZEEBE_BROKER_DATA_BACKUP_S3_SECRETKEY
            value: "{{workflow.parameters.ZEEBE_BROKER_DATA_BACKUP_S3_SECRETKEY}}"
          - name: ZEEBE_BROKER_DATA_BACKUP_S3_REGION
            value: "{{workflow.parameters.ZEEBE_BROKER_DATA_BACKUP_S3_REGION}}"
          - name: ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT
            value: "{{workflow.parameters.ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT}}"
          - name: ZEEBE_BROKER_CLUSTER_CLUSTERSIZE
            value: "{{workflow.parameters.ZEEBE_BROKER_CLUSTER_CLUSTERSIZE}}"
          - name: ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR
            value: "{{workflow.parameters.ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR}}"
  - name: scale-up-camunda
    steps:
    - - name: upgrade-camunda
        templateRef:
                name: upgrade-camunda
                template: upgrade-camunda
        arguments:
          parameters:
          - name: release-name
            value: "{{workflow.parameters.RELEASE_NAME}}"
          - name: helm-namespace
            value: "{{workflow.parameters.NAMESPACE}}"
          - name: values-file
            value: "{{workflow.parameters.VALUE_FILE}}"
          - name: zeebe-cluster-size
            value: "3"
          - name: operate-enabled
            value: "true"
          - name: optimize-enabled
            value: "true"
          - name: tasklist-enabled
            value: "true"
          - name: connectors-enabled
            value: "true"
