apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: istio-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.22.3
    chart: istiod
  destination:
    namespace: istio-system
    server: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
#  dependencies: []