apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway-{{ .Values.spec.multiRegion.clusterName }}
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:ManuelDittmar/camunda-deployment.git
    path: helm/multi-region/istio/istio-gateway
    targetRevision: HEAD
    helm:
      valueFiles:
        - {{ .Values.spec.multiRegion.clusterName }}/values.yaml
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: istio-system
  syncPolicy:
    automated:
      selfHeal: true