istiod:
  global:
    meshID: camunda-mesh
    multiCluster:
      enabled: true

  pilot:
    autoscaleEnabled: true
    autoscaleMin: 1
    autoscaleMax: 5
    resources:
      requests:
        cpu: 500m
        memory: 2048Mi

  gateways:
    istio-ingressgateway:
      enabled: true

  meshConfig:
    enablePrometheusMerge: true