apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-secret-access-binding
subjects:
- kind: ServiceAccount
  name: argo-workflow
  namespace: camunda
roleRef:
  kind: ClusterRole
  name: argo-workflow-secret-access
  apiGroup: rbac.authorization.k8s.io