apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multiregion-primary
  namespace: argo-cd
spec:
  generators:
    - list:
        elements:
          - name: istio-base
            chart: base
            targetRevision: "1.22.3"
            valuesFile: values/primary/istio-base-values.yaml
          - name: istiod
            chart: istiod
            targetRevision: "1.22.3"
            valuesFile: values/primary/istiod-values.yaml
            dependencies: [istio-base]
          - name: istio-ingressgateway
            chart: gateway
            targetRevision: "1.22.3"
            valuesFile: values/primary/istio-ingressgateway-values.yaml
            dependencies: [istiod]
          - name: kiali
            chart: kiali-operator
            targetRevision: "1.87.0"
            valuesFile: values/primary/kiali-values.yaml
            dependencies: [istio-ingressgateway]
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: 'git@github.com:ManuelDittmar/camunda-deployment.git'
        chart: '{{chart}}'
        targetRevision: '{{targetRevision}}'
        helm:
          valueFiles:
            - '{{valuesFile}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true