apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: elastic-delete-indices
spec:
  templates:
  - name: elastic-delete-indices
    inputs:
      parameters:
      - name: elasticsearch-endpoint
    container:
      image: curlimages/curl
      command: ["/bin/sh", "-c"]
      args: 
      - |
        # Define Elasticsearch endpoint
        elasticsearch_endpoint="{{inputs.parameters.elasticsearch-endpoint}}"
        
        # List all non-system indices (excluding those starting with .)
        indices=$(curl -s "$elasticsearch_endpoint/_cat/indices?h=index" | grep -v '^\.')
        
        # Delete each index individually
        for index in $indices; do
          echo "Deleting index: $index"
          curl -X DELETE "$elasticsearch_endpoint/$index"
        done
        
        echo "All non-system indices have been deleted."
    restartPolicy: Never
